### PR TITLE
Add Vote Extension processing logic for side txs

### PR DESCRIPTION
**Pull request by Raneet10**
# Description

This PR enables voting for side txs using [Vote Extensions from CometBFT](https://github.com/cometbft/cometbft/blob/main/spec/abci/abci++_methods.md#extendvote). This would eventually replace sidechannel mechanism, which is used for the same in the present.

Please note that the core V.E processing logic has a few dependencies on yet-to-be implemented modules and hence are commented out for now.

# Changes

- [ ] Bugfix (non-breaking change that solves an issue)
- [ ] Hotfix (change that solves an urgent issue, and requires immediate attention)
- [x] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (change that is not backwards-compatible and/or changes current functionality)
- [ ] Changes only for a subset of nodes

# Checklist

- [x] I have added at least 2 reviewer or the whole pos-v1 team
- [x] I have added sufficient documentation in code
- [x] I will be resolving comments - if any - by pushing each fix in a separate commit and linking the commit hash in the comment reply

## Testing

- [ ] I have added unit tests
- [ ] I have added tests to CI
- [ ] I have tested this code manually on local environment
- [ ] I have tested this code manually on remote devnet using express-cli
- [ ] I have tested this code manually on mumbai
- [ ] I have created new e2e tests into express-cli

### CODE REVIEW

**Review by lasarojc — COMMENTED** [review]
I've done a first pass mostly overlooking the comments addressed at Informal. I will do another one looking into these.

**Review by lasarojc — COMMENTED** [review]
> Is it okay to not follow the [convention](https://github.com/0xPolygon/cosmos-sdk/blob/507ec1de34858aed7872e60a096f043a975ab3c9/simapp/abci.go#L39) here 👀 ? 

Sure. They don't follow it themselves.

**Review by lasarojc — COMMENTED** [review]
I see what you mean. `canAddVE` means that the proposal for the current height, the one being extended, could include the `ExtendedVoteInfo` from the previous height. 
If the inclusion is a possibilty only, then the second `if` should not panic when it doesn't find the special transaction.
If `canAddVE` will be extended to respond true only when the special transaction is expected, then this function LGTM.
A simpre approach might be to prefix the marshalled special transaction with some reserved set of bits and check for their presence instead or in compelement to using `canAddVE`.

**Review by glnro — COMMENTED** [review]
I highly recommend adding some unit tests for `vote_ext_processor.go`

**Pull request merged**
